# Site settings
title: Rick Hocutt
email: rick.hocutt@gmail.com
description: Personal Portfolio website of Rick Hocutt
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rickhocutt.com" # the base hostname & protocol for your site
twitter_username: RickHocutt
github_username:  RickHocutt

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - bower_components
  - node_modules

collections:
  portfolio:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
